# Generated by Django 5.0.6 on 2026-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(default=0.0)),
                ('dimension_scores', models.JSONField(default=dict)),
                ('compatibility_highlights', models.JSONField(default=list)),
                ('user_a_action', models.CharField(choices=[('pending', '等待'), ('liked', '心动'), ('passed', '再想想')], default='pending', max_length=10)),
                ('user_b_action', models.CharField(choices=[('pending', '等待'), ('liked', '心动'), ('passed', '再想想')], default='pending', max_length=10)),
                ('status', models.CharField(choices=[('pending', '等待双方确认'), ('matched', '双向心动'), ('missed', '已错过')], default='pending', max_length=10)),
                ('week_number', models.CharField(max_length=10)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('action_deadline', models.DateTimeField()),
            ],
            options={
                'verbose_name': '匹配',
                'verbose_name_plural': '匹配',
            },
        ),
    ]
