# Generated by Django 5.0.6 on 2026-05-09 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
                ('code_type', models.CharField(choices=[('email', '邮箱验证'), ('phone', '手机验证')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '验证码',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='male', max_length=10)),
                ('gender_preference', models.CharField(choices=[('male', '男'), ('female', '女'), ('both', '不限')], default='female', max_length=10)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('freshman', '大一'), ('sophomore', '大二'), ('junior', '大三'), ('senior', '大四'), ('master1', '研一'), ('master2', '研二'), ('master3', '研三'), ('phd', '博士')], max_length=20, null=True)),
                ('college_direction', models.CharField(blank=True, choices=[('stem', '理工'), ('humanities', '文史'), ('art', '艺术设计'), ('business', '经管'), ('medicine', '医学'), ('other', '其他')], max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('active', '正常'), ('banned', '封禁'), ('deleted', '注销')], default='active', max_length=10)),
                ('questionnaire_completion', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '黑名单',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
